name: Create a ZIP for Thunderstore upload

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: BittaLethalPack${{ github.run_number }}
          path: |
            CHANGELOG.md
            LICENSE
            README.md
            icon.png
            manifest.json
